"""users table

Revision ID: 8efc1cd613ec
Revises: b9d8f4be610a
Create Date: 2019-12-31 18:17:03.656532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8efc1cd613ec'
down_revision = 'b9d8f4be610a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=60), nullable=True))
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('post_ibfk_1', 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
